version: '3'
services:
  
  nextcloud-server:
    image: nextcloud:28.0.6-fpm
    container_name: nextcloud-server
    hostname: nextcloud-server
    environment:
      - MYSQL_DATABASE=ncdb
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=nextcloud-db
    volumes:
      - ./dev-environment-data/server:/var/www/html
    depends_on:
      - nextcloud-db
    restart: unless-stopped
    networks:
      - nextcloud-network

  nextcloud-nginx:
    image: nginx
    container_name: nextcloud-nginx
    hostname: nextcloud-nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dev-environment-data/server:/var/www/html:ro
    depends_on:
      - nextcloud-server
    networks:
      - nextcloud-network

  nextcloud-db:
    container_name: nextcloud-db
    hostname: nextcloud-db
    restart: unless-stopped
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ncdb
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - ./dev-environment-data/db:/var/lib/mysql
    networks:
      - nextcloud-network

networks:
  nextcloud-network: