services:
  nextcloud-container:
    build:
      context: .
      dockerfile: Dockerfile.Nextcloud
      args:
        - NEXTCLOUD_VERSION=${NEXTCLOUD_VERSION:-30.0.0}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG:-1}
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-develop}
    ports:
      - "80:80"
    privileged: true
    # cap_add:
    #   - SYS_PTRACE
    #   - SYS_ADMIN
    #   - NET_ADMIN
    container_name: nextcloud-container
    hostname: nextcloud-container
    depends_on:
      - smtp
    restart: unless-stopped
    networks:
      nextcloud-network:
      static-network:
        ipv4_address: 172.20.128.2
  smtp:
    image: rnwood/smtp4dev:v3
    container_name: smtp
    hostname: smtp
    restart: unless-stopped
    environment:
      ServerOptions__DisableIPv6: true
    ports:
      - "8081:80"
    networks:
      - nextcloud-network

networks:
  nextcloud-network:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.5.0/24
