ARG NEXTCLOUD_VERSION=29.0.5

FROM nextcloud:${NEXTCLOUD_VERSION}

RUN apt update && apt install -y less vim telnet iputils-ping
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN install-php-extensions gd xdebug
COPY xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
