version: "3.8"
services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: unsafe
      MYSQL_USER: mysql
      MYSQL_PASSWORD: unsafe
      MYSQL_DATABASE: nextcloud
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

  nextcloud:
    image: nextcloud:stable
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: unsafe
      MYSQL_DATABASE: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: redis
    ports:
     - "80:80"
     - "443:443"
    restart: unless-stopped
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:stable
    volumes:
      - nextcloud_data:/var/www/html
    entrypoint: /cron.sh
    restart: unless-stopped
    depends_on:
      - db
      - redis

volumes:
  db_data: {}
  nextcloud_data: {}
