name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build 
      run: make build

    - name: Create artifact 
      run: make appstore

    - uses: actions/upload-artifact@v4
      with:
        name: gdata-antivirus
        path: build/artifact
