name: Makefile CI

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      nextcloud_versions: ${{ steps.get-matrix.outputs.nextcloud_versions }}
    steps:
      - uses: actions/checkout@v4
      - id: get-matrix
        run: echo "nextcloud_versions=$(./get-matrix.sh)" | tee -a "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        nextcloud_version: ${{fromJson(needs.define-matrix.outputs.nextcloud_versions)}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: setup node
        with:
          node-version: 20

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.11.0

      - name: replace version in ./appinfo/info.xml
        if: startsWith(github.ref, 'refs/tags/')
        id: replace-version-in-info
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          sed -i "s/<version>0.0.0<\/version>/<version>$RELEASE_VERSION<\/version>/g" ./appinfo/info.xml

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: unittests
        env:
          CLIENT_ID: ${{ secrets.VAAS_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.VAAS_CLIENT_SECRET }}
        run: |
          composer install --quiet
          ./vendor/bin/phpunit --bootstrap tests/unittests/bootstrap.php tests/unittests/ --testdox

      - uses: docker-practice/actions-setup-docker@master
      - name: install nextcloud
        env:
          CLIENT_ID: ${{ secrets.VAAS_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.VAAS_CLIENT_SECRET }}
        run: ./install.sh ${{ matrix.nextcloud_version }}

      - name: run tests
        env:
          CLIENT_ID: ${{ secrets.VAAS_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.VAAS_CLIENT_SECRET }}
        run: bats --no-parallelize-across-files --jobs 2 ./tests/bats

      - uses: actions/upload-artifact@master
        with:
          overwrite: true
          name: build-dir
          path: build/

  release:
    needs:
      - test
      - define-matrix
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@master
        with:
          name: build-dir
          path: build/

      - name: write version to output
        id: write-version-to-output
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/artifacts/*

      - name: Attach tarball to github release
        uses: svenstaro/upload-release-action@v2
        id: attach_to_release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/artifacts/gdatavaas.tar.gz
          asset_name: gdatavaas.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload app to Nextcloud appstore
        uses: nextcloud-releases/nextcloud-appstore-push-action@v1
        with:
          app_name: gdatavaas
          appstore_token: ${{ secrets.VAAS_APPSTORE_TOKEN }}
          download_url: ${{ steps.attach_to_release.outputs.browser_download_url }}
          app_private_key: ${{ secrets.VAAS_NEXTCLOUD_KEY }}
